name: SnesOnline
options:
  bundleIdPrefix: com.snesonline
  # Pin the generated .xcodeproj format to Xcode 15.x so GitHub Actions
  # macos-14 runners (Xcode 15.4) can open it.
  xcodeVersion: "15.4"
  deploymentTarget:
    iOS: "14.0"
settings:
  base:
    SWIFT_VERSION: 5.0
    CLANG_CXX_LANGUAGE_STANDARD: "c++17"
    CLANG_CXX_LIBRARY: "libc++"
    SWIFT_OBJC_BRIDGING_HEADER: app/Sources/SnesOnline-Bridging-Header.h
    HEADER_SEARCH_PATHS:
      - "$(SRCROOT)/../../include"
      - "$(SRCROOT)/.."
    OTHER_CPLUSPLUSFLAGS:
      - "-std=c++17"

targets:
  SnesOnline:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: SnesOnline
        EXECUTABLE_NAME: "$(PRODUCT_NAME)"
        WRAPPER_NAME: "$(PRODUCT_NAME).app"
        PRODUCT_BUNDLE_IDENTIFIER: com.snesonline.snesonline
        INFOPLIST_FILE: app/Info.plist
        ALWAYS_SEARCH_USER_PATHS: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"
    sources:
      - path: app/Sources
      - path: ../ios
        includes:
          - SNESOnlineIOSBridge.mm
          - SNESOnlineIOSNative.mm
      - path: ../../src
      - path: ../../include
      - path: app/Resources
        buildPhase: resources
        type: folder
      - path: app/Assets.xcassets
        buildPhase: resources
